- package.json
- packages/controls/package.json
- packages/controls/tests/__snapshots__/MaskedInput.test.js.snap
- packages/date/package.json
- packages/dialog/package.json
- packages/messages/package.json
- packages/money/package.json
- packages/notifications/package.json
- packages/router/package.json
- packages/tproptypes/package.json
- tools/pkgupgrade.js
- yarn.lock
> * Added a dependency updater tool

- packages/dialog/package.json
- packages/mongoloader/tests/MongoLoader.test.js
- packages/mongoloader/tests/mongo.js
* Fixed deployment of @thx/dialog
* Enhanced mongoloader test. (there was a problem but fix was installing libcurl13 on ubuntu 18.04)
> Fix @thx/dialog deployment

- packages/controls/src/form/TForm/TForm.js
- packages/controls/src/inputs/ScriptelInput/ScriptelInput.js
Add an check to see if the data value is empty or not and render the according component.
closes darkadept/thr4#294.
> ScriptelInput&TformUpdate

- packages/controls/src/inputs/AddDynamicFormInput/AddDynamicFormInput.tsx
- packages/controls/tests/inputs/__snapshots__/AddDynamicFormInput.test.js.snap
It can now handle masked Inputs as a child of Form.Input.
> Updated the AddDynamicFormInput component. 

- packages/controls/src/date/DatePicker/styles.css
Increases the width of the date input to match literally every other input.
> added 100% width to date wrapper to add consistancy with other inputs

- packages/controls/src/date/TimeDropdown/TimeDropdown.tsx
- packages/controls/tests/date/__snapshots__/TimeDropdownTest.test.js.snap
> The time in the TimeDropdown component is not showing properly when the minute is set to zero.

- packages/extras/src/common/mimeCheck.ts
> Reject office documents for now

- .circleci/config.yml
- packages/controls/src/money/MoneyInput/MoneyInput.tsx
- packages/controls/src/money/MoneyInput/moneyinput.stories.tsx
* Fixed money input. Closes #173
* updated circleci config
> Fix money input

- packages/controls/src/money/MoneyInput/MoneyInput.tsx
- packages/controls/src/money/MoneyInput/moneyinput.stories.tsx
> MoneyInput now doesn't break on undefined value.

- packages/controls/src/date/DatePicker/styles.css
> Fixed DatePicker popper z index.

- packages/date/src/__snapshots__/formatDate.test.ts.snap
- packages/date/src/formatDate.test.ts
- packages/date/src/formatDate.ts
> Fixed default values and added tests for formatDate

- packages/controls/src/inputs/Scriptel/Scriptel.tsx
- packages/controls/src/inputs/Scriptel/ScriptelContext.ts
- packages/controls/src/inputs/Scriptel/scriptel/enums.ts
- packages/controls/src/inputs/Scriptel/scriptel/index.ts
- packages/controls/src/inputs/Scriptel/scriptel/messages.ts
- packages/controls/src/inputs/ScriptelInput/ScriptelInput.tsx
> Updated the Scriptel input to show loading indicator

- packages/controls/src/inputs/Scriptel/Scriptel.tsx
> fix(controls): fixed scriptel input loading indicator

- packages/controls/src/inputs/ScriptelInput/ScriptelInput.tsx
- packages/controls/src/inputs/ScriptelInput/scriptelinput.stories.tsx
> feat(controls): added ability to change button text on scriptelInput,

- packages/controls/src/inputs/ScriptelInput/ScriptelInput.tsx
- packages/controls/src/yupTypes/scriptelSchemaType.test.ts
- packages/controls/src/yupTypes/scriptelSchemaType.ts
> feat(controls): added a JS timestamp to the signature data

- packages/controls/src/date/MonthYearPicker/MonthYearPicker.tsx
- packages/controls/src/date/MonthYearPicker/monthyearpicker.stories.tsx
> feat(controls): fixed monthYear picker component

- packages/controls/src/inputs/Scriptel/Scriptel.tsx
- packages/controls/src/inputs/Scriptel/scriptel/index.ts
- packages/controls/src/inputs/ScriptelInput/scriptelinput.stories.tsx
> Scriptel loading indicator fix

- packages/mikroorm-types/src/LocalDateProperty.ts
- packages/mikroorm-types/src/__snapshots__/LocalDateProperty.test.ts.snap
> fix(mikroorm-types): changed local date property type

- packages/controls/src/money/MoneyInput/MoneyInput.tsx
> fix(controls): fixed money input

- packages/controls/src/index.ts
- packages/controls/src/money/MoneyCurrencyInput/MoneyCurrencyInput.tsx
- packages/controls/src/money/MoneyCurrencyInput/index.ts
- packages/controls/src/money/MoneyCurrencyInput/moneycurrencyinput.stories.tsx
- packages/controls/src/money/MoneyInput/MoneyInput.tsx
- packages/controls/src/money/MoneyInput/moneyinput.stories.tsx
- packages/controls/src/money/useMoneyInput.ts
> feat(controls): created money currency input

- packages/env/src/Environment.ts
- packages/env/src/env.ts
- packages/env/src/getCorsOrigin.ts
- packages/env/src/index.ts
- yarn.lock
feat(env): add new env functions to access the environment
> refactor(env): deprecated Environment class

- package.json
- packages/controls/src/date/LocalDatePicker/LocalDatePicker.tsx
- yarn.lock
> Date picker fixes
